service:
    apply: prod
    workername : productionsrv
    brokercleanjobs : true
    administrator_mail : Me <me@domain.com>
    notifications_scan: true
    # demo_worker: true

javamail:
    from: Me <me@domain.com>
    server: exchange.domain.com
    debug: false
    port : 587
    auth : true
    starttls : true
    username : me
    password : mypasswd

log2:
    filter:
        -
            for: hd3gtv.mydmam.pathindexing
            level: INFO
            type: DEFAULT
        -
            for: hd3gtv.mydmam.manager
            level: INFO
            type: DEFAULT
        -
            for: hd3gtv.mydmam.ssh.SshLogger
            level: INFO
            type: HIDE
        -
            for: hd3gtv.mydmam.db
            level: INFO
            type: DEFAULT
    rotate_file: /var/log/mydmam/server.log 
    rotate_maxsize: 1000000
    rotate_maxfilelogs: 10

