service:
    workername : productionsrv
    brokercleanjobs : true
    administrator_mail : Me <me@domain.com>
    notifications_scan: true
    # debug_multiple_workers: false
    # 
    # Full/off hours configuration
    # CyclicJobCreator with only_off_hours parameter, use "fullhours" syntax.
    # Hours are in 24h style, one entry by line, example:
    #       - 8-12
    #       - 14-19
    # for activate off hours Cyclic only from 0 PM to 8 AM, and from 12 PM to 7 PM.
    # From time is included, end time is excluded.

javamail:
    from: Me <me@domain.com>
    server: exchange.domain.com
    debug: false
    port : 587
    auth : true
    starttls : true
    username : me
    password : mypasswd
    # groovy_debug: true
