service:
    apply: prod
    workername : productionsrv
    brokercleantasks : true

javamail:
    from: Me <me@domain.com>
    to: admin@domain.com 
    server: exchange.domain.com
    debug: false

log2:
    filter:
        -
            for: hd3gtv.javasimpleservice.ServiceWorker$1.run
            level: INFO
            type: HIDE
        -
            for: hd3gtv.javasimpleservice.ServiceManager$1.run
            level: INFO
            type: HIDE
        -
            for: hd3gtv.mydmam.probe.Scan
            level: INFO
            type: DEFAULT
        -
            for: hd3gtv.mydmam.pathindexing.Importer
            level: INFO
            type: DEFAULT
        -
            for: hd3gtv.mydmam.task.Task.createTask
            level: DEBUG
            type: ONE_LINE
        -
            for: hd3gtv.mydmam.ssh.SshLogger
            level: INFO
            type: HIDE
        -
            for: hd3gtv.mydmam.taskqueue.Broker.getNextJob
            level: DEBUG
            type: HIDE
    rotate_file: /var/log/mydmam/server.log 
    rotate_maxsize: 1000000
    rotate_maxfilelogs: 10

